---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chartname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      serviceAccountName: {{ .Release.Name }}-serviceaccount
      containers:
      - name: {{ template "name" . }}
        image: "{{.Values.image.repo}}"
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{.Values.service.port}}
        env:
        - name: CLUSTERMANAGERAPI_PORT
          value: "{{.Values.service.port}}"
        {{- if .Values.helpers.aws.enabled }}
        - name: CLUSTERMANAGERAPI_CMAAWS_ENDPOINT
          value: "{{.Values.helpers.aws.endpoint }}"
        - name: CLUSTERMANAGERAPI_CMAAWS_INSECURE
          value: "{{.Values.helpers.aws.insecure }}"
        {{- end }}
        {{- if .Values.helpers.aks.enabled }}
        - name: CLUSTERMANAGERAPI_CMAAKS_ENDPOINT
          value: "{{.Values.helpers.aks.endpoint }}"
        - name: CLUSTERMANAGERAPI_CMAAKS_INSECURE
          value: "{{.Values.helpers.aks.insecure }}"
        {{- end }}
        {{- if .Values.helpers.vmware.enabled }}
        - name: CLUSTERMANAGERAPI_CMAVMWARE_ENDPOINT
          value: "{{.Values.helpers.vmware.endpoint }}"
        - name: CLUSTERMANAGERAPI_CMAVMWARE_INSECURE
          value: "{{.Values.helpers.vmware.insecure }}"
        {{- end }}
        {{- if .Values.helpers.ssh.enabled }}
        - name: CLUSTERMANAGERAPI_CMASSH_ENDPOINT
          value: "{{.Values.helpers.ssh.endpoint }}"
        - name: CLUSTERMANAGERAPI_CMASSH_INSECURE
          value: "{{.Values.helpers.ssh.insecure }}"
        {{- end }}
        - name: CLUSTERMANAGERAPI_KUBERNETES_NAMESPACE
          value: "{{ .Release.Namespace}}"
