# Default values.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: cluster-manager-api
image:
   repo: quay.io/samsung_cnct/cluster-manager-api:0.1.8

port: 80
service:
   port: 80
   type: ClusterIP
ingress:
   rest:
      name: cma
      host: cma.cnct.io
   grpc:
      name: cma-grpc
      host: cma-grpc.cnct.io
issuer:
   email: someone@cnct.io
   region: us-east-1
   accesskey:
      id: ""
      secret: ""
   hostedzoneid: ""

helpers:
   aks:
      enabled: false
      endpoint: cma-aks-cma-aks:80
      insecure: true
   aws:
      enabled: false
      endpoint: cma-aws-cma-aws:80
      insecure: true
   vmware:
      enabled: false
      endpoint: cma-vmware-cma-vmware:80
      insecure: true
   ssh:
      enabled: false
      endpoint: cma-ssh:80
      insecure: true
